### ISSUE TITLE
Network testing result is not in accord with the settings

### ISSUE THREAD

**Issue by SummerHaze** [facebook/augmented-traffic-control#103]
Hi,
After building the running environment well ,I use www.speedtest.net to test the bandwidth(both download and upload ) and latency of the simulated network.
However, it seems the test result is not in accord with the settings on 127.0.0.1:8000.
For example,when I set it like this:
uplink------bandwidth:50kbps，Delay:500ms
downlink------bandwidth:50kbps，Delay:500ms
My test result is(Average,testing on iphone):
uplink------bandwidth:747kbps
downlink------bandwidth:276kbps
Delay------239ms

I've tried other speedtest tools,too.But no one can match the expectation.

May I know your testing methods? Or make a recommendation？
BTW, is bandwidth setting( uplink/downlink) on the management web the average or the maximum value?

**Comment by chantra** [comment]
Hi @SummerHaze 
So you will most likely never get the exact numbers using a speedtest,  #90 goes over some of the details. In a nutshell, TCP will start retransmitting packets... and the bandwith you assign are going to be different than what the speedtest report.

That being said, in you case, the link is faster than what you have set.... so basically, you most likely not have set shaping for your device.
You mention `127.0.0.1:8000` .... did you start the shaping locally? If you want to shape let say your iphone, you must connect to the UI using your iphone and turn on shaping from your iphone.
In your specific case, you are most likely shaping 127.0.0.1, which turns out to not shape as shape tagging is applied upon forwarding packets.

> May I know your testing methods? Or make a recommendation？

#90 will answer this question

> BTW, is bandwidth setting( uplink/downlink) on the management web the average or the maximum value?

Some burst can happen, but it is safe to say it is the maximum.

**Comment by SummerHaze** [comment]
hi，chantra.
Thank you for your suggestion. I really shaped the network on the 127.0.0.1:8000 instead of the client's ip, like 192.168.2.3:8000.
As for the testing methods , I've read the #90 issue but can't find a way to do it （：<）.

Could you please make some suggestions，too?

Any help dealing with this will be greatly appreciated.

**Comment by SummerHaze** [comment]
Could I use chariot to measure it?

**Comment by SummerHaze** [comment]
Can I use Chariot to measure the network traffic instead of the speedtest?

**Comment by chantra** [comment]
@SummerHaze  I am not sure how chariot works, but in a nutshell, you want to test at IP level, not TCP and you want to run your tests from devices that are as close as possible to the ATC box to rule out latency added by other hops.

If the test use TCP, then you will get the bandwith that accounts for packet retransmission....

Also, I just realized that I linked the wrong issue, it should have been #86 .

**Comment by chantra** [comment]
Closing this as the original issue was that the traffic was not being shaped. You could use iperf to perform tests. If #86 does not explain the discrepancy you may find, feel free to open another task.
