### ISSUE TITLE
Getting 404 error on augmented-traffic-control

### ISSUE THREAD

**Issue by arvindsawant** [facebook/augmented-traffic-control#133]
Hi 
I am facing a issue, while configure ATC in browser as proxy it gives me 404 error 

{u'path': u'http://Webserver hostname/'}
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

I run "atcd --atcd-wan eth0 --atcd-lan eth0" and "atcd --atcd-lan eth0" still facing same issue.

my config is
Centos 6.5 and I have installed ATC  in which I have eth0 for intranet and same is natted with Public IP for internet too via firewall. So can you guide me how can I resolve issue?

**Comment by chantra** [comment]
Hi @arvindsawant 
First of all, `atcd` needs to separate interfaces to be able to function, while they may be the same physical device, they need to have different names (so eth0 and eth1 for instance).

Second, the ATC UI error you are seeing will be unrelated to atcd. The UI could be running standalone without atcd, but will need to eventually connect to atcd to trigger shaping, displaying the UI would not fail though.

Lastly, I am not sure how you got this 404. From what you pasted, it seems that the path is set `http://webserver.hostname/` instead of something like `atc_demo_ui/` .
You mentioned a proxy, I wonder if your issue is somehow similar to: http://stackoverflow.com/questions/4622488/django-application-works-on-development-server-but-i-get-404-on-apache
If you bypass the proxy, can you successfully load atc ui?

**Comment by arvindsawant** [comment]
As per your suggestion I have put two physical card in system eth0 – 10.50.249.216 (netted with public IP) and eth1- 10.50.248.2 (separate network for augmented-traffic-control) and was able to setup shaping. 

now can you please suggest how to test this on device or Mobile. Can we use that 10.50.248.2 IP as gatway or proxy IP on device?
http://10.50.248.2:8000/atc_demo_ui/ - Profile Create and its show turn on and turn off option too.
http://10.50.248.2:8000/api/v1/shape - its also working.
http://10.50.248.2:8000/api/v1/profiles/ 
http://10.50.249.216:8000/api/v1/token/
When we use 10.50.248.2 as gateway internet does not work and when we use 10.50.248.2 IP as proxy and port 8000 it gives 404 error {u'path': u'http://google.com/'}  

so please help me to know how to test this setup.

**Comment by chantra** [comment]
Hi @arvindsawant
Atc UI is not a proxy so do not try to use it as a proxy as it will not work.
Yes you will need to use 10.50.248.2 as gateway. This route will the pass on packets to the upstream router in 10.50.249.216's network.

Atcd requirement is to run on a routing device. Until the device that will run atcd is able to route packets properly you can take atcd out of the picture.
Setting a router is out of the scope here and I will refer you to resources available on Google for your favorite Linux OS. There could be many reasons why your routing is not working: ip forwarding not set, upstream router not knowing how to route back to the clients subnet.... From what you describe I think it may be the latter.
Once you have your router working, I believe atcd will work out of the box and will be happy to help from there on if you still have issues. For the time being I will close this issue until you have a functional routing device to run atc on.
