### ISSUE TITLE
Rate Discrepancy

### ISSUE THREAD

**Issue by JamshedVesuna** [facebook/augmented-traffic-control#195]
I am seeing a higher throughput than what ATC should be limiting at. 

I looked at #86, #90, and #135, but everything seems to be running correctly. I have a client that is accessing / changing the ATC rate through the web UI, running an iperf test (`iperf -c <ip addr> -p 2000 -t 10 -i 2`). The client is connected to an intermediary host that is running ATC and forwarding all traffic on port 2000 to an end server using iptables. The intermediary is connected to an end server that is running an iperf server.

When ATC is turned off, I am seeing 7.66 Mbits/sec. When ATC is turned on with the "Edge - Average" profile (copied below), I am seeing 1.25 Mbits/sec, where it should be 200 kb/s.

So ATC does seem to be limiting the rate, just not at the right value? I'm positive there is another factor here.

```
{
  "down": {
    "rate": "240",
    "delay": {
      "delay": "400",
      "jitter": 0,
      "correlation": 0
    },
    "loss": {
      "percentage": "0",
      "correlation": 0
    },
    "reorder": {
      "percentage": 0,
      "correlation": 0,
      "gap": 0
    },
    "corruption": {
      "percentage": 0,
      "correlation": 0
    },
    "iptables_options": []
  },
  "up": {
    "rate": "200",
    "delay": {
      "delay": "440",
      "jitter": 0,
      "correlation": 0
    },
    "loss": {
      "percentage": "0",
      "correlation": 0
    },
    "reorder": {
      "percentage": 0,
      "correlation": 0,
      "gap": 0
    },
    "corruption": {
      "percentage": 0,
      "correlation": 0
    },
    "iptables_options": []
  }
}
```

**Comment by zfjagann** [comment]
Try running iperf with a longer time period (like 60 or 120 seconds). Does this produce more realistic network speeds?

In general in my testing I've seen bandwidth be a little higher than ATC should let it be, but only over short time intervals. Testing over a longer time interval should give you a more realistic measurement.

**Comment by JamshedVesuna** [comment]
I ran with both 60 second and 300 seconds, and did not see a significant change (less than 0.2 Mb/s change from the original). I also tried running with the `--atcd-dont-drop-packets` flag, but that didn't seem to make a difference here.

**Comment by chantra** [comment]
@JamshedVesuna you say you are forwarding all the traffic to a given port to a separate host. You are most likely using data for that.
This will cause the gateway to only be able to shape traffic in 1 direction. No natting should be done before the atc gateway. The only scenario that work is when you do masquerade on the want link only.

**Comment by chantra** [comment]
s/want/wan/

**Comment by JamshedVesuna** [comment]
@chantra You're correct, I am only shaping traffic in one direction (upload to the server). Can you explain this a bit further? My impression of an `iperf` speedtest was that it is a bulk transfer of bytes in a single direction.

**Comment by chantra** [comment]
@JamshedVesuna we do mark packets using iptables, outgoing with source of the shaped device are marked on the lan  interface and shaped on the wan . Incoming are marked on the wan interface and shaped on the lan. In your case incoming on the wan have a destination set to the atc box (your nat  rules is causing that) and never get marked, hence never shaped on the downstream direction.
Iperf defaults to tcp, there is so many packets you can send with tcp without being acked. You are getting lower rate because eventually the downstream is becoming the bottleneck.
In any case, natting  prevents atc from being able to do its job and it is a requirement that natting is not used. You can masquerade on the outgoing interface because that will not get into the way of atc (this is quite long to explain but you can refer to iptables  flow chart if you want to get more details).

**Comment by chantra** [comment]
I will close this issue as it is not meeting atc requirements. If you want to run tests you will need to use a host upstream of atc.
