### ISSUE TITLE
API should not fail if atcd is not running

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#206]
If the API cannot connect to atcd, this is something we will want to report to the user, but the api should still run.
```
root@2822036df305:/usr/src/myapp# ./bin/atc_api -4 127.0.0.1
2015/12/03 17:53:00 failed to connect to atcd server: dial tcp 127.0.0.1:9090: getsockopt: connection refused
```

**Comment by chantra** [comment]
oh, I see we have the `--warn` argument....

**Comment by zfjagann** [comment]
You still want this fixed? I figure this is desired behavior, but you can suppress it with the `--warn` argument.

**Comment by chantra** [comment]
It kind of forces the daemon to be up before the api.... what happen if it starts fine and then the daemon goes down. How do we handle this?

**Comment by zfjagann** [comment]
If the daemon goes down while the API is running, future requests that require the daemon (all of them except those related to profiles) will fail with a 502 error.

I think having `--warn` available, but not the default is the best way to do this. It avoids situations where you start `atc_api` up with the wrong thrift address before the `atcd` server, but ignore the log message since you started them in the wrong order.

**Comment by chantra** [comment]
Yeah, i dont have strong feeling provided that there is a way to to bypass it and that it is properly handled during runtime.
Just for the sake of clarity I will add a more explanatory error message.
