### ISSUE TITLE
Support multiple LAN and WAN interfaces

### ISSUE THREAD

**Issue by jkrauska** [facebook/augmented-traffic-control#234]
Our linux router has multiple LAN and WAN interfaces.

Primary LAN and Guest LAN. (eth0 eth1)
Primary ISP uplink and Secondary ISP uplink (eth2, eth3)

It would be ideal to support the LAN and WAN definitions as arrays/lists instead of single strings.

Not sure if marking rules need to be applied in a more generic manner and if other unexpected oddities might pop up.. (is a 1Mbit rate limit on two interfaces actually a 2Mbit link in total? -- does async routing cause a problem)

But having the general ability would be awesome.

**Comment by zfjagann** [comment]
I've been playing around with this idea for a while.

In your specific case do both LAN interfaces represent the same physical LAN segment? Or are you using two separate LANs and the ATC box is routing between them?
Will you ever want to shape traffic from eth0 to eth1?

**Comment by chantra** [comment]
@jkrauska How are you using those 2 ISP uplinks? Are you bonding the interfaces? in this case, you could use atcd on the bond interface.

for the multiple lan, the issue is that even if we were going to support it, we would not be able to properly defined the limits and a host would potentially be able to get 1M through Primary LAN, and 1M through uplinks.

**Comment by zfjagann** [comment]
I'm going to close this because it's been inactive for a while. Please re-open if you have any other questions.
