### ISSUE TITLE
How to reslove these error messages during the ATC running

### ISSUE THREAD

**Issue by ctriptest** [facebook/augmented-traffic-control#244]
Hi team,

I have successfully let the ATC run up, I found this error message (pic) during the ATC running, would you please guide me how to solve it?
Thanks a lot!
![atc error](https://cloud.githubusercontent.com/assets/16544057/13395861/54314196-df2c-11e5-8a25-7df7baae6e75.jpg)

**Comment by zfjagann** [comment]
Do you have a desktop available? I'm interested to see what the javascript console in chrome looks like, but on mobile there's not an easy way to get at this information.

If you're using chrome on desktop, you can get to the console by using `Options` -> `More Tools` -> `Developer Tools` and then clicking on the `Console` tab. If you then refresh the page, you should get more information about what is causing this issue.

**Comment by ctriptest** [comment]
@zfjagann 
I cannot reproduce this error to used the chrome browser on desktop (Ubuntu OS).
Now, I only told you when these errors occur, I cannot turn off the profiles and the network status of mobile become to offline.

**Comment by ctriptest** [comment]
Hi team,

Today, I get another warning message (pic1), would you have any information for this warning?
![atc warning](https://cloud.githubusercontent.com/assets/16544057/13450538/7bd7dad4-e071-11e5-8843-60f30ca7c004.jpg)

**Comment by zfjagann** [comment]
Unfortunately it's really difficult for me to tell what's going on without seeing the output from the chrome console. When I designed the UI, I didn't consider that the console wouldn't be available for mobile devices. Clearly there are improvements to be made here.

Does the page work for you besides the notifications? I.e. can you still use the page to shape your traffic normally, or are these notifications preventing this from working correctly?
If the notifications aren't keeping you from shaping your traffic you can tap the grey "Notifications" bar and it should hide that pane. This will allow you to use the page normally.

**Comment by ctriptest** [comment]
@zfjagann 
Thanks for your information.
The ATC cannot work that I saw the notifications, and the page visit will timeout or always loading.
So, I can not continue with the network simulation on the phone, my aim is to test the performance of APP within narrowband network environment.

**Comment by chantra** [comment]
@zfjagann @ctriptest 
I think this can happen for 2 reasons:

1. the atc server and the device are not using ntp, the time drifts on one of the device making the auth token invalid.That would be fixed by making sure that NTP is used.
2. https://github.com/facebook/augmented-traffic-control/blob/60e38611a535273c887a0a08ff94286ab19ecd9b/atc/django-atc-demo-ui/atc_demo_ui/static/js/atc-auth.js#L36 I wonder if there could be a race condition where the token just issued expires the next second. I would expect this to be solved by reloading the page. https://github.com/facebook/augmented-traffic-control/blob/60e38611a535273c887a0a08ff94286ab19ecd9b/atc/atcd/atcd/access_manager.py

**Comment by ctriptest** [comment]
@chantra 

Thanks for your information.
I will try to rebulid the ATC, then I will give you nore feedback in the fetrue.
