### ISSUE TITLE
ugly page view

### ISSUE THREAD

**Issue by easternHong** [facebook/augmented-traffic-control#253]
[ugly page view ](https://testerhome.com/topics/2889#reply54)

*   the same view in chrome and firefox.

i dont kown ,what happen to this.

```
my env:
django-admin version  : 1.9.4
python : 2.7
```

**Comment by chantra** [comment]
Hi @easternHong 

This is a duplicate of #216 and the root cause is https://github.com/no-dice/django-bootstrap-themes/issues/2

It should be fixed since https://pypi.python.org/pypi/django-bootstrap-themes/3.1.3 was released.

check the output of `pip freeze` and make sure
django-bootstrap-themes has version 3.1.3

I am pretty sure this will fix your issue, I will close this issue in the meantime, please open a new one if you still have issues.
