### ISSUE TITLE
Network Traffic Routing configuration

### ISSUE THREAD

**Issue by vikastiger** [facebook/augmented-traffic-control#262]
Hi - My ATC setup is as per the following details:

- OS - Ubuntu 14.04 on x86 server (no virtualization)
- Hostname - 'piano'
- Network interfaces - eth0 (192.168.1.0 network) as Internet facing, eth1 (10.10.10.0 network) for DHCP

Till the point of DHCP configuration, it looks to work fine ... the DHCP server on Ubuntu is allocating IP addresses (say 10.10.10.2) to my other machine when i connect (wired) it directly to piano's eth1.

Below are the contents of some key files on 'piano' for reference:

/etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
address 192.168.1.2
netmask 255.255.255.0
broadcast 192.168.1.255
gateway 192.168.1.1
dns-nameservers 192.168.1.1

auto eth1
iface eth1 inet static
address 10.10.10.1
netmask 255.255.255.0
broadcast 10.10.10.255

/etc/dhcp/dhcpd.conf
ddns-update-style none;
option domain-name "example.org";
option domain-name-servers 192.168.1.1;
default-lease-time 600;
max-lease-time 7200;
authoritative;
log-facility local7;
subnet 10.10.10.0 netmask 255.255.255.0 {
interface eth1;
range 10.10.10.3 10.10.10.254;
option subnet-mask 255.255.255.0;
option broadcast-address 10.10.10.255;
option routers 10.10.10.1;
}

/etc/default/isc-dhcp-server
INTERFACES="eth1"

cat /etc/resolv.conf

Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

nameserver 192.168.1.1

My ip forwarding is enabled.

Now i am facing two problems that is:
1- Unable to access internet until i run " sudo dhclient " command. After that it works fine.
2- Now at other interface which is connected to wifi router is not giving internet to devices.

i can also ping to 8.8.8.8 .

I configured it 10 months ago and it was working good but a week ago it stopped working. Please Help .

**Comment by chantra** [comment]
@vikastiger

For 1) Are you saying that the ubuntu host which you provided the config here (which acts as a router) is not able to access internet until you run `dhclient` ?
This is not related to ATC and does not make a lot of sense given that piano is setup to use static ips.

2) I don't understand what you mean by the other interface connected to wifi router? is this eth0 of piano?


You did not mention iptables and masquerade. This is something that you will most likely need if you want the traffic to be routed back to the devices.

**Comment by vikastiger** [comment]
yes, correct until i run dhclient internet is not accessible.

i am attaching a draw of my network config.

[network draw.docx](https://github.com/facebook/augmented-traffic-control/files/269761/network.draw.docx)

and i ran these commands at the time of setup:

iptables -A FORWARD -o eth0 -i eth1 -s 10.10.10.0/24 -m conntrack --ctstate NEW -j ACCEPT

iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

iptables -t nat -F POSTROUTING

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

**Comment by chantra** [comment]
@vikastiger ok, this is definitely not an ATC problem and you should try to get support from communities related to your specific distro.
ATC requires a working routing platform to operate, once you have this, we can happily help you with getting ATC to work.

That being said, a few reasons why your device connected to router 2 may not be able to connect:
router 2 is not in bridge mode and is not natting (and should not otherwise you will not be able to shape any individual devices but will shape the whole router 2 network) and you have not told the ubuntu host how to send traffic back to the network behind router 2.
For instance if router 2 give ips in range 10.10.11.0/24, you should add a route to that network via router 2 (something along `ip route add 10.10.11.0/24 via 10.10.10.2` ) assuming you statically configure router 2 with 10.10.10.2.
You will also need to accept forwarding for that specific network on your ubuntu box.

**Comment by chantra** [comment]
@vikastiger I will close this issue for now as this is not an ATC issue, you will get better support from your distribution community, they will be able to help you correctly set and configure your system.
Once you have the routing working, we can happily help you with atc specific issues/questions.
