### ISSUE TITLE
ATC - questions 

### ISSUE THREAD

**Issue by cgavriluta** [facebook/augmented-traffic-control#281]
Total linux noob here, but following Jason's tutorial (http://www.jasonernst.com/2016/04/04/turning-a-netgear-r7000-into-an-augmented-traffic-control-router/) I managed to install ATC on my R7000 wireless router and everything seems to be working (I can start the daemon, start and access the django UI, etc). I have a couple of questions though:
1. Are there some linux commands to see the changes that the atcd demon does to the routing table? I would like to see what changes after I make a modification in the django UI. 
2. It seems that only the internet-traffic is being shaped. If this is true, is there a way to shape the local traffic? To be more explicit: I want, for example, two laptops connected to the router to exchange data between them as if they were on a 2G network.

**Comment by zfjagann** [comment]
1. ATC doesn't directly change the routing table, since packets are routed over the host already. Instead, it uses iptables to signal any packets that should be marked to be handled differently by tc than other packets.
You can use `iptables-save` to see what the current iptables rules are (including which IP addresses are being shaped).
You can use `tc {object}  list` to view current tc objects (`class`, `filter`, `qdisc`). This will show you what the settings for the shaping are.
You'll need to run these commands as root for them to work correctly.

2. This isn't something the current version of ATC can do easily, although if you have a spare router, you could have each laptop connect to two separate ATC instances and you could make this work with some tinkering.

Thank you for trying out ATC, let us know if you have any other questions. :smile:
