### ISSUE TITLE
need any configuration to forward traffic from eth0 to eth1

### ISSUE THREAD

**Issue by Amolwale** [facebook/augmented-traffic-control#99]
i have installed atc on my ubuntu machine which having two ethernet eth0 and eth1 but 
it will not shape the traffic.

whether i have to make any configuration  like ip forwarding, NATing to forward traffic from eth0 to eth1.

or ATC will do that with the help of iproute2

**Comment by chantra** [comment]
Hi @Amolwale ,

Is the traffic you are trying to shape forwarded by your Ubuntu machine? e.g is you ubuntu machine acting as a routing hop for the devices you want to shape the traffic for?

**Comment by Amolwale** [comment]
yes,
my eth0 connected to the WAN   
and eth1 connected to the client machine, on which i want to shape the traffic.

i also tried for various ways to ping from eth0 to eth1.
 to ensure that, at least eth0 and eth1 is communicating for atc but not getting the solution

**Comment by chantra** [comment]
I think I missed read this task.... Are you saying that the traffic is not being shaped? Or not being forwarded?

If you were taking ATC out of the picture, does your device route properly?
ATC will only take care of shaping the traffic, so you should make sure you have a functional routing device first. There is plenty of documentation on the internet for this.

**Comment by yogesh5655** [comment]
hello friend
I am facing the same problem as amol said i have to route traffic from eth1 (2nd interface of Controller PC and eth0 is connected to Internet)to eth0 (LAN interface)...pls help for routing...

**Comment by yogesh5655** [comment]
hi
 can i use ubuntu's inbuilt option i.e. shared to other computer
 for forwarding internet traffic from eth0 (WAN) to eth1(LAN)
or if you have any other solution please suggest me

**Comment by chantra** [comment]
@yogesh5655 @Amolwale 

I am not sure what Ubuntu internet sharing entails, but I think we can safely assume that it will set up ip forwarding + natting.
From the examples I see on the internet, I am not sure it will set a DHCP server on your behalf though, so you will have to set this yourself, or set static ips to the devices.
There is plenty of tutorial on the internet that would cover any of those settings for your favorite Linux distribution.

**Comment by chantra** [comment]
@Amolwale @yogesh5655 
In order to have ATC shaping your traffic, it needs to be on a host that routes and forward the traffic. ATC will not take care of setting this up, it's sole purpose is to shape the traffic that is routed, not to configure the router to route.
So prior to setting ATC, make sure your device can route and forward the traffic correctly.

Also, from the same host, pinging each other interface is only triggering some local traffic, not forwarded traffic.

At this stage, it is not an ATC problem but rather setting a router. There is documentation on the internet that should help you setting your favorite distribution as a router.
I will close this task, feel free to open a new one when you have a functioning router and have issue with ATC itself.
I am more than happy to help with setting up routing on the ATC host, but I would take this discussion to a more interactive channel on #atcd irc channel on Freenode.

**Comment by arvindsawant** [comment]
Hi 
I am facing a issue, while configure ATC in browser as proxy it gives me 404 error 

{u'path': u'http://Webserver hostname/'}
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

I run "atcd --atcd-wan eth0 --atcd-lan eth0" and "atcd --atcd-lan eth0" still facing same issue.

my config is
Centos 6.5 and I have installed ATC  in which I have eth0 for intranet and same is natted with Public IP for internet too via firewall. So can you guide me how can I resolve issue?
